import numpy as np

A = np.array([[1, 2], [-1, 1]])
B = np.array([[2, 0], [0, 2]])
C = np.array([[2, 0, -3], [0, 0, -1]])
D = np.array([[1, 2], [2, 3], [-1, 0]])
x = np.array([[1], [0]])
y = np.array([[0], [1]])
z = np.array([[1], [2], [-1]])

np.save("A4.npy", A + B)
print(A + B)
np.save("A5.npy", 3 * x - 4 * y)
print(3*x - 4*y)
np.save("A6.npy", A.dot(x))
print(A.dot(x))
np.save("A7.npy", B.dot(x - y))
print(B.dot(x - y))
np.save("A8.npy", D.dot(x))
print(D.dot(x))
np.save("A9.npy", D.dot(y) + z)
print(D.dot(y) + z)
np.save("A10.npy", A.dot(B))
print(A.dot(B))
np.save("A11.npy", B.dot(C))
print(B.dot(C))
np.save("A12.npy", C.dot(D))
print(C.dot(D))
